### ISSUE TITLE
Offline API

### ISSUE THREAD

**Issue by victorgveloso** [MarceloVilela/scrapping#1]
![image](https://user-images.githubusercontent.com/11022419/118392061-e358a680-b60d-11eb-806a-8c9c46dd4bc2.png)

![image](https://user-images.githubusercontent.com/11022419/118392076-03886580-b60e-11eb-860f-f3a055bc676e.png)

Both links are down. Is the deployed version up to date with the master branch? Is this problem source code related? Is it host related? Does hosting it locally work?

**Comment by MarceloVilela** [comment]
host changed. New adresses added on about and readme.md.

Note: address #1 stopped running and waiting for more free dyno hours next month on heroku

**Comment by victorgveloso** [comment]
Thanks for replying quickly. You should check qovery, it's an alternative to heroku with free hosting plan for up to 3 applications (https://www.qovery.com/). It also offers storage options (sql and nosql)
